# Generated by Django 3.1.2 on 2020-11-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=170)),
                ('exp', models.CharField(max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('detail', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('img_event', models.ImageField(upload_to='')),
                ('url_sistem', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
