# Generated by Django 3.1.2 on 2020-11-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_sistem',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
