# Generated by Django 3.1.2 on 2020-11-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201111_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentOnay',
        ),
    ]
