# Generated by Django 3.1.2 on 2020-11-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_commentonay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='one_cikar',
        ),
        migrations.DeleteModel(
            name='OneCikarilanlar',
        ),
    ]
