# Generated by Django 3.1.2 on 2020-11-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='news',
            field=models.BooleanField(default=False),
        ),
    ]
